ai:
    platform:
        # Inference Platform configuration
        # see https://github.com/symfony/ai/tree/main/src/platform#platform-bridges

        # openai:
        #    api_key: '%env(OPENAI_API_KEY)%'
        
        ollama:
            http_client: 'ollama.client'
        
        gemini:
            api_key: '%env(GEMINI_API_KEY)%'


    agent:
        # Agent configuration
        # see https://symfony.com/doc/current/ai/bundles/ai-bundle.html

        default:
           platform: 'ai.platform.gemini'
           model: 'gemini-2.5-flash-lite'
           prompt: |
                Sen idefix için çalışan Türkçe müşteri destek chatbotusun.
                Cevapların kısa, net ve sadece Türkçe olsun.
           
        #    platform: 'ai.platform.openai'
        #    model: 'gpt-5-mini'
        #    prompt: |
        #        Sen Türkçe cevap veren yardımcı bir asistansın.
        #        Cevapların kısa, net ve anlaşılır olsun.
        #    tools:
        #        - 'Symfony\AI\Agent\Bridge\Clock\Clock'

    store:
        # Store configuration

        # chromadb:
        #    default:
        #        client: 'client.service.id'
        #        collection: 'my_collection'
