<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260519105742 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE EXTENSION IF NOT EXISTS vector');
        $this->addSql('CREATE EXTENSION IF NOT EXISTS unaccent');

        $this->addSql(<<<'SQL'
CREATE TABLE rag_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    tenant_id UUID NULL,
    document_id VARCHAR(190) NOT NULL,
    source_path TEXT NOT NULL,
    source_url TEXT DEFAULT NULL,
    source_type VARCHAR(32) NOT NULL,
    title TEXT DEFAULT NULL,
    language VARCHAR(10) NOT NULL DEFAULT 'tr',
    content_type VARCHAR(100) NOT NULL,
    checksum CHAR(64) NOT NULL,
    token_count INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_indexed_at TIMESTAMPTZ DEFAULT NULL,
    CONSTRAINT uq_rag_sources_public_id UNIQUE (public_id),
    CONSTRAINT uq_rag_sources_tenant_document UNIQUE (tenant_id, document_id),
    CONSTRAINT chk_rag_sources_token_count CHECK (token_count >= 0)
)
SQL);

        $this->addSql(<<<'SQL'
CREATE TABLE rag_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES rag_sources(id) ON DELETE CASCADE,
    tenant_id UUID NULL,
    document_id VARCHAR(190) NOT NULL,
    embedding_model VARCHAR(64) NOT NULL DEFAULT 'embeddinggemma',
    embedding_dims SMALLINT NOT NULL DEFAULT 768,
    chunk_no INTEGER NOT NULL,
    heading TEXT DEFAULT NULL,
    content TEXT NOT NULL,
    content_hash CHAR(64) NOT NULL,
    token_count INTEGER NOT NULL,
    char_count INTEGER NOT NULL,
    start_offset INTEGER DEFAULT NULL,
    end_offset INTEGER DEFAULT NULL,
    language VARCHAR(10) NOT NULL DEFAULT 'tr',
    content_type VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    embedding VECTOR(768) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_rag_chunks_source_chunk UNIQUE (source_id, chunk_no),
    CONSTRAINT chk_rag_chunks_dims CHECK (embedding_dims > 0),
    CONSTRAINT chk_rag_chunks_token_count CHECK (token_count > 0),
    CONSTRAINT chk_rag_chunks_char_count CHECK (char_count > 0),
    CONSTRAINT chk_rag_chunks_chunk_no CHECK (chunk_no >= 0)
)
SQL);

        $this->addSql('CREATE INDEX idx_rag_sources_tenant_active ON rag_sources (tenant_id, is_active)');
        $this->addSql('CREATE INDEX idx_rag_sources_type_lang ON rag_sources (source_type, language)');
        $this->addSql('CREATE INDEX idx_rag_sources_metadata ON rag_sources USING GIN (metadata jsonb_path_ops)');

        $this->addSql('CREATE INDEX idx_rag_chunks_source_active ON rag_chunks (source_id, is_active, chunk_no)');
        $this->addSql('CREATE INDEX idx_rag_chunks_filter ON rag_chunks (tenant_id, is_active, language, content_type, embedding_model)');
        $this->addSql('CREATE INDEX idx_rag_chunks_metadata ON rag_chunks USING GIN (metadata jsonb_path_ops)');

        // $this->addSql("CREATE INDEX idx_rag_chunks_tsv_tr ON rag_chunks USING GIN (to_tsvector('pg_catalog.simple', unaccent(coalesce(heading, '') || ' ' || content)))");

        $this->addSql('CREATE INDEX idx_rag_chunks_embedding_hnsw ON rag_chunks USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 128)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS rag_chunks');
        $this->addSql('DROP TABLE IF EXISTS rag_sources');
    }
}
